# SOPS Configuration for IaC Learning Template
# This file defines encryption rules for secrets management
#
# IMPORTANT: Replace 'YOUR_AGE_PUBLIC_KEY_HERE' with your actual Age public key
#            Run: age-keygen -y .secrets/age.key
#            Or: task sops:keygen

creation_rules:
  # Encrypt all files matching .sops.* pattern with Age
  - path_regex: .*\.sops\.(yaml|yml|json|env)$
    age: YOUR_AGE_PUBLIC_KEY_HERE

# Age Key File Location (set in environment or .envrc)
# export SOPS_AGE_KEY_FILE="${PWD}/.secrets/age.key"

# Usage Examples:
#   sops -e secrets/app.sops.env        # Encrypt
#   sops -d secrets/app.sops.env        # Decrypt
#   sops secrets/app.sops.env           # Edit in-place
#   task sops:edit                      # Edit via Task
#   task sops:view                      # View decrypted
