# SOPS Configuration
# Replace YOUR_AGE_PUBLIC_KEY_HERE with output from: age-keygen -y .secrets/age.key

creation_rules:
  - path_regex: .*\.sops\.(yaml|yml|json|env)$
    age: YOUR_AGE_PUBLIC_KEY_HERE

# Age key location (set via direnv in .envrc)
# export SOPS_AGE_KEY_FILE="${PWD}/.secrets/age.key"
