# IaC Learning Template - Prometheus Configuration
# Educational example of monitoring configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'iac-learning'
    project: 'template'

# === Alerting Configuration ===
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# === Rule Files ===
rule_files:
  # - "alerts/*.yml"

# === Scrape Configurations ===
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          
  # Nginx web server
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'web'
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # PostgreSQL database (example - would need postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
        labels:
          service: 'database'
    scrape_interval: 30s
    
  # Redis cache (example - would need redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
        labels:
          service: 'cache'
    scrape_interval: 30s
    
  # Container metrics (example - would need cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'containers'
    scrape_interval: 30s
