---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Example services and demonstrations
version: '3'

tasks:
  # === Quick Demo Commands ===
  up:
    desc: "🚀 Start example services"
    cmds:
      - task: compose:up
      
  demo:
    desc: "🎭 Interactive demo of IaC concepts"
    cmds:
      - task: demo:overview
      - task: demo:secrets
      - task: demo:services
      - task: demo:monitoring
      
  advanced:
    desc: "🔮 Advanced IaC automation examples"
    cmds:
      - task: demo:scaling
      - task: demo:backup
      - task: demo:security
      
  # === Demo Sections ===
  demo:overview:
    desc: "📊 Show infrastructure overview"
    cmds:
      - |
        echo "=== Infrastructure Overview ==="
        echo ""
        echo "🏢 Our example infrastructure includes:"
        echo "  📊 Database: PostgreSQL with initialization"
        echo "  🚀 Cache: Redis for session storage"
        echo "  🌐 Web: Nginx reverse proxy"
        echo "  📈 Monitoring: Prometheus + Grafana"
        echo "  🔍 Health: Automated health checks"
        echo ""
        echo "🔐 Security features:"
        echo "  ✅ SOPS encrypted secrets"
        echo "  ✅ Non-root containers"
        echo "  ✅ Network isolation"
        echo "  ✅ Resource limits"
        echo ""
        
  demo:secrets:
    desc: "🔐 Demonstrate secrets management"
    cmds:
      - |
        echo "=== Secrets Management Demo ==="
        echo ""
        echo "🔑 Age key location: .secrets/age.key"
        echo "📝 SOPS config: .sops.yaml"
        echo ""
        
        if [[ -f "{{.ROOT_DIR}}/secrets/app.sops.env" ]]; then
          echo "👀 Encrypted secrets file contents (first 5 lines):"
          head -5 "{{.ROOT_DIR}}/secrets/app.sops.env"
          echo "..."
          echo ""
          
          echo "🔓 Decrypted secrets preview:"
          echo "(Showing non-sensitive fields only)"
          sops --decrypt "{{.ROOT_DIR}}/secrets/app.sops.env" | grep -E "^(DB_HOST|REDIS_HOST|APP_ENV)=" || echo "No preview available"
          echo ""
        fi
        
        echo "📚 Learn more: 'task sops:tutorial'"
        
  demo:services:
    desc: "🐳 Demonstrate service orchestration"
    cmds:
      - |
        echo "=== Service Orchestration Demo ==="
        echo ""
        
        if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" 2>/dev/null | grep -q "."; then
          echo "✅ Services currently running:"
          docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --format table
          echo ""
          
          echo "🌐 Service endpoints:"
          echo "  Nginx: http://localhost:8080"
          echo "  Grafana: http://localhost:3000 (admin/admin)"
          echo "  Prometheus: http://localhost:9090"
          echo ""
          
          echo "📈 Health check results:"
          for service in nginx postgres redis prometheus; do
            if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | grep -q "$service"; then
              echo "  ✅ $service: healthy"
            else
              echo "  ❌ $service: not running"
            fi
          done
        else
          echo "ℹ️  No services running. Start with: task up"
        fi
        
  demo:monitoring:
    desc: "📈 Demonstrate monitoring setup"
    cmds:
      - |
        echo "=== Monitoring Demo ==="
        echo ""
        
        # Check if monitoring is available
        if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | grep -q "prometheus"; then
          echo "✅ Prometheus monitoring active"
          echo "🌎 URL: http://localhost:9090"
          echo ""
          
          # Show example metrics
          echo "📈 Example metrics being collected:"
          echo "  - Container CPU/Memory usage"
          echo "  - Database connections"
          echo "  - HTTP request rates"
          echo "  - System health checks"
          echo ""
          
          if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | grep -q "grafana"; then
            echo "✅ Grafana dashboards available"
            echo "🌎 URL: http://localhost:3000"
            echo "👤 Login: admin/admin"
          fi
        else
          echo "⚠️  Monitoring services not running"
          echo "💡 Start with: task up"
        fi
        
  # === Advanced Demos ===
  demo:scaling:
    desc: "📈 Demonstrate service scaling"
    cmds:
      - |
        echo "=== Service Scaling Demo ==="
        echo ""
        
        if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | grep -q "nginx"; then
          echo "📈 Current nginx instances:"
          docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps nginx
          echo ""
          
          echo "🚀 Scaling nginx to 3 instances..."
          docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" up -d --scale nginx=3
          
          echo "📈 New nginx instances:"
          docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps nginx
          
          echo ""
          echo "🔄 Scaling back to 1 instance..."
          docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" up -d --scale nginx=1
        else
          echo "⚠️  Services not running. Start with: task up"
        fi
        
  demo:backup:
    desc: "💾 Demonstrate backup procedures"
    cmds:
      - |
        echo "=== Backup Procedures Demo ==="
        echo ""
        
        # Database backup simulation
        if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | grep -q "postgres"; then
          echo "💾 Creating database backup..."
          
          # Create backup directory
          mkdir -p "{{.ROOT_DIR}}/examples/backups"
          
          # Simulate backup (in real scenario, this would be actual pg_dump)
          echo "📁 Backup location: examples/backups/"
          echo "📅 Backup timestamp: $(date)"
          echo "📊 Backup size: simulated 150MB"
          
          # Create example backup metadata
          cat > "{{.ROOT_DIR}}/examples/backups/backup-$(date +%Y%m%d).info" << EOF
        Backup Information
        ==================
        Date: $(date)
        Database: postgres
        Size: 150MB (simulated)
        Type: Full backup
        Encryption: AES-256
        Status: Completed
        EOF
          
          echo "✅ Backup completed successfully"
          echo "📝 Backup info saved to: examples/backups/backup-$(date +%Y%m%d).info"
        else
          echo "⚠️  Database not running. Start with: task up"
        fi
        
  demo:security:
    desc: "🔒 Demonstrate security features"
    cmds:
      - |
        echo "=== Security Features Demo ==="
        echo ""
        
        echo "🔐 Secrets Management:"
        echo "  ✅ Age encryption for sensitive data"
        echo "  ✅ SOPS integration for GitOps workflows"
        echo "  ✅ No plaintext secrets in repository"
        echo ""
        
        echo "🐳 Container Security:"
        if docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | head -1 | grep -q "."; then
          echo "  ✅ Non-root user containers"
          echo "  ✅ Read-only root filesystems"
          echo "  ✅ Resource limits applied"
          echo "  ✅ Network segmentation"
          
          # Show security details for a service
          service_name=$(docker compose -f "{{.ROOT_DIR}}/examples/docker-compose.yml" ps --services --filter "status=running" | head -1)
          if [[ -n "$service_name" ]]; then
            echo ""
            echo "🔍 Security details for $service_name:"
            docker inspect "$(docker compose -f {{.ROOT_DIR}}/examples/docker-compose.yml ps -q $service_name | head -1)" --format '  User: {{.Config.User}}' 2>/dev/null || echo "  User: default"
            echo "  ReadonlyRootfs: enabled"
            echo "  ResourceLimits: configured"
          fi
        else
          echo "  ⚠️  No running containers to inspect"
        fi
        
        echo ""
        echo "🌐 Network Security:"
        echo "  ✅ Internal service communication"
        echo "  ✅ Port exposure only where needed"
        echo "  ✅ Environment isolation"
