---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Docker Compose operations with SOPS secrets integration
version: '3'

tasks:
  up:
    desc: "Start services with secrets injection"
    cmds:
      - |
        echo "🚀 Starting services with encrypted secrets..."
        if [[ -f "{{.ENC_ENV}}" ]]; then
          if grep -q "sops_" "{{.ENC_ENV}}" 2>/dev/null; then
            echo "🔐 Decrypting SOPS secrets..."
            export $(sops --decrypt "{{.ENC_ENV}}" | grep -v '^#' | xargs)
          else
            echo "📝 Loading plaintext environment..."
            set -a && source "{{.ENC_ENV}}" && set +a
          fi
        else
          echo "⚠️  No environment file found at {{.ENC_ENV}}"
          echo "💡 Run 'task sops:init' to create encrypted secrets"
        fi
        echo "🐳 Starting Docker Compose services..."
        docker compose -f "{{.COMPOSE_FILE}}" up -d
        echo "✅ Services started successfully"
    preconditions:
      - sh: test -f "{{.COMPOSE_FILE}}"
        msg: "Docker Compose file not found: {{.COMPOSE_FILE}}"
        
  down:
    desc: "Stop all services"
    cmds:
      - |
        echo "🛑 Stopping services..."
        docker compose -f "{{.COMPOSE_FILE}}" down
        echo "✅ Services stopped"
        
  ps:
    desc: "List running services"
    cmds:
      - |
        echo "📊 Service Status:"
        docker compose -f "{{.COMPOSE_FILE}}" ps
        
  logs:
    desc: "Show logs for services (usage: task compose:logs -- <service>)"
    cmds:
      - |
        if [[ -n "{{.CLI_ARGS}}" ]]; then
          echo "📝 Logs for service: {{.CLI_ARGS}}"
          docker compose -f "{{.COMPOSE_FILE}}" logs -f {{.CLI_ARGS}}
        else
          echo "📝 Logs for all services:"
          docker compose -f "{{.COMPOSE_FILE}}" logs -f
        fi
        
  restart:
    desc: "Restart services (usage: task compose:restart -- <service>)"
    cmds:
      - |
        if [[ -n "{{.CLI_ARGS}}" ]]; then
          echo "🔄 Restarting service: {{.CLI_ARGS}}"
          docker compose -f "{{.COMPOSE_FILE}}" restart {{.CLI_ARGS}}
        else
          echo "🔄 Restarting all services..."
          docker compose -f "{{.COMPOSE_FILE}}" restart
        fi
        
  shell:
    desc: "Get shell access to service (usage: task compose:shell -- <service>)"
    cmds:
      - |
        if [[ -z "{{.CLI_ARGS}}" ]]; then
          echo "❌ Service name required. Usage: task compose:shell -- <service>"
          exit 1
        fi
        echo "🐚 Opening shell in service: {{.CLI_ARGS}}"
        docker compose -f "{{.COMPOSE_FILE}}" exec {{.CLI_ARGS}} /bin/bash || 
        docker compose -f "{{.COMPOSE_FILE}}" exec {{.CLI_ARGS}} /bin/sh
        
  pull:
    desc: "Pull latest images"
    cmds:
      - |
        echo "⬇️ Pulling latest images..."
        docker compose -f "{{.COMPOSE_FILE}}" pull
        echo "✅ Images updated"
